In [58]:
import numpy as np

In [68]:
a=np.arange(4).reshape(2,2)
b=np.arange(5,9).reshape(2,2)

In [69]:
a,b

(array([[0, 1],
        [2, 3]]),
 array([[5, 6],
        [7, 8]]))

In [70]:
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [71]:
np.linalg.inv(b)

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [72]:
np.linalg.det(a)

-2.0

In [73]:
np.linalg.det(b)

-1.999999999999999

In [74]:
np.linalg.eig(a)

(array([-0.56155281,  3.56155281]),
 array([[-0.87192821, -0.27032301],
        [ 0.48963374, -0.96276969]]))

In [75]:
np.linalg.eig(b)

(array([-0.15206735, 13.15206735]),
 array([[-0.75868086, -0.59276441],
        [ 0.65146248, -0.80537591]]))

In [94]:
c=np.arange(9).reshape(3,3)
d=np.arange(5,14).reshape(3,3)

c,d

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]]))

In [95]:
np.linalg.eig(c)

(array([ 1.33484692e+01, -1.34846923e+00, -1.26963291e-15]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

In [96]:
np.linalg.eig(d)

(array([ 2.76509717e+01, -6.50971698e-01,  1.42621701e-15]),
 array([[-0.37636677, -0.75529416,  0.40824829],
        [-0.55798202, -0.05094566, -0.81649658],
        [-0.73959727,  0.65340284,  0.40824829]]))

In [97]:
np.linalg.det(c)

0.0

In [98]:
np.linalg.det(d)

0.0

In [99]:
e=np.array([0,30,45,60,90])

In [100]:
np.sin(e)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [101]:
np.cos(e)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [102]:
np.tan(e)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

In [103]:
np.sinh(e)

array([0.00000000e+00, 5.34323729e+12, 1.74671355e+19, 5.71003695e+25,
       6.10201647e+38])

In [104]:
np.cosh(e)

array([1.00000000e+00, 5.34323729e+12, 1.74671355e+19, 5.71003695e+25,
       6.10201647e+38])

In [105]:
np.tanh(e)

array([0., 1., 1., 1., 1.])